/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from 'three';

export default function AvatarBody(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/avatar.glb");

  return (
    <group>
      <group ref={group} {...props} dispose={null}>
        <group
          position={[0, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.5}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh.geometry}
            material={materials.Tshirt_Green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={materials.LightSkin}
          />
        </group>
      </group>
    </group>

  );
}

useGLTF.preload("/avatar.glb");