/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import AvatarBody from "./avatarBody";
import AvatarHead from "./avatarHead";
import Controller from './controller';
import React, { useState, useEffect } from "react";
import { useThree, useFrame } from '@react-three/fiber';


export default function Avatar(props) {

  useFrame((state, delta) => {
    // This function runs at the native refresh rate inside of a shared render-loop
    state.controls.target = state.scene.children[1].position
    // console.log("pointer", state.events.handlers.onClick())
  })

  //Updating Camera Controls
  return (
    <group name="player" position={[0, 280, 0]}>
      <AvatarBody position={[0, 0, 0]} />
      <AvatarHead position={[0, 25, 0]} />
      <Controller/>
    </group>

  );
}
