/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import AvatarBody from "./avatarBody";
import { Circle, Planes } from "@react-three/drei";
import * as THREE from 'three';

export default function Avatar(props) {

    let video = document.createElement('video');
    video.width = 320;
    video.height = 240;
    video.autoplay = true;

    //Camera Detection

    if (navigator.mediaDevices.getUserMedia) {
        navigator.mediaDevices.getUserMedia({ video: true })
          .then(function (stream) {
            video.srcObject = stream;
          })
          .catch(function (err0r) {
            console.log("Something went wrong!");
          });
      }

    let videoTexture = new THREE.Texture( video );

    return (
        <group position={[0.01, 260, 0]}>
            <Circle args={[8, 50]} position={[0, 23, 0]}>
                <meshBasicMaterial attach="material" map={videoTexture} opacity={0.5} transparent/>
            </Circle>
            <AvatarBody />
        </group>
    );
}
